DROP TABLE IF EXISTS "transactions";
DROP TABLE IF EXISTS "accounts";

CREATE TABLE "accounts" (
    "ID"          UUID PRIMARY KEY,
    "CUSTOMER_ID" VARCHAR(255) NOT NULL,
    "BALANCE"     DECIMAL(19, 2) NOT NULL,
    "VERSION"     BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE "transactions" (
    "ID"          UUID PRIMARY KEY,
    "ACCOUNT_ID"  UUID NOT NULL,
    "AMOUNT"      DECIMAL(19, 2) NOT NULL,
    "TYPE"        VARCHAR(20) NOT NULL,
    "STATUS"      VARCHAR(20) NOT NULL,
    "CREATED_AT"  TIMESTAMP NOT NULL,
    CONSTRAINT "FK_TRANSACTIONS_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "accounts" ("ID")
);